import type { SiteConfig } from "../types/siteConfig";

export const siteConfig: SiteConfig = {
	title: "Hailuo4ever",
	subtitle: "My Personal Blog",
	site_url: "https://blog.hailuo4ever.com/",
	description:
		"Hailuo 的个人博客，记录算法学习、竞赛题解、课程笔记与日常生活。",
	keywords: ["Hailuo", "算法", "竞赛题解", "学习笔记", "个人博客"],
	themeColor: {
		hue: 150,
		defaultMode: "system",
	},
	pageWidth: 100,
	card: {
		border: false,
		followTheme: false,
	},
	favicon: [
		{
			src: "/favicon/favicon-light-32.png",
			sizes: "32x32",
			theme: "light",
		},
		{
			src: "/favicon/favicon-dark-32.png",
			sizes: "32x32",
			theme: "dark",
		},
	],
	navbar: {
		logo: {
			type: "icon",
			value: "material-symbols:home",
		},
		title: "Hailuo4ever",
		widthFull: false,
		menuAlign: "center",
		followTheme: false,
		navbarMode: "dynamic",
	},
	siteStartDate: "2026-04-24",
	timezone: "Asia/Shanghai",
	categoryBar: true,
	categoryStyle: "rectangle",
	tagStyle: "pill",
	foldArticle: true,
	postListLayout: {
		defaultMode: "list",
		mobileDefaultMode: "list",
		coverPosition: "right",
		descriptionLines: 2,
		showStatsIcons: true,
		tagsPosition: "bottom",
		tagsBottomStyle: "chip",
		meta: {
			showPublished: true,
			showCategory: true,
			showTags: true,
			tagCount: 3,
			showWords: false,
			showReadingTime: false,
		},
		stats: {
			showPublished: true,
			showWords: true,
			showReadingTime: true,
		},
		grid: {
			masonry: false,
			columnWidth: 320,
			coverFullWidth: false,
		},
	},
	pagination: {
		postsPerPage: 10,
	},
	post: {
		rehypeCallouts: {
			theme: "github",
			enablePythonMarkdownAdmonitions: false,
		},
		showLastModified: true,
		outdatedThreshold: 30,
		share: true,
		postNavigation: true,
		relatedPosts: true,
		randomPosts: true,
		generateOgImages: false,
		immersiveReading: {
			enable: true,
			defaultOn: false,
			tocEnabled: true,
			tocPosition: "left",
		},
	},
	bilibili: {
		uid: "",
	},
	bangumi: {
		userId: "",
		mode: "dynamic",
		apiUrl: "https://api.bangumi.pro",
		subjectBaseUrl: "https://api.bangumi.pro/subject/",
		categoryOrder: ["anime", "book", "music", "game"],
		nsfw: "hide",
	},
	vndb: {
		userId: "",
		mode: "static",
		downloadCovers: false,
		apiUrl: "https://api.vndb.org/kana",
		vnBaseUrl: "https://vndb.org/",
		apiToken: "",
		nsfw: "hide",
	},
	mal: {
		username: "",
		clientId: "",
		apiUrl: "https://api.myanimelist.net/v2",
		animeBaseUrl: "https://myanimelist.net/anime/",
		mangaBaseUrl: "https://myanimelist.net/manga/",
		nsfw: "hide",
	},
	imageOptimization: {
		formats: "webp",
		quality: 85,
		noReferrerDomains: [
			"*.hdslb.com",
			"*.bilibili.com",
			"*.myanimelist.net",
			"*.vndb.org",
		],
	},
	lang: "zh_CN",
	pages: {
		friends: true,
		guestbook: false,
		dynamic: false,
		gallery: false,
		booknav: false,
		bilibili: false,
		bangumi: false,
		vndb: false,
		mal: false,
		sponsor: false,
	},
};
